/* DO NOT EDIT THIS FILE - it is machine generated */
#include <iostream>
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <opencv2/highgui/highgui.hpp>

#include <dlib/opencv.h>
#include <dlib/image_processing/frontal_face_detector.h>
#include <dlib/image_processing/render_face_detections.h>
#include <dlib/image_processing.h>
#include <dlib/gui_widgets.h>

/* Header for class com_harish_faciallandmarkdetection_NativeClass */

using namespace cv;
using namespace dlib;
using namespace std;

#ifndef _Included_com_harish_faciallandmarkdetection_NativeClass
#define _Included_com_harish_faciallandmarkdetection_NativeClass
#ifdef __cplusplus
extern "C" {
#endif

void faceDetection(Mat& img, Mat& dst);
void renderToMat(std::vector<full_object_detection>& dets, Mat& dst);

/*
 * Class:     com_harish_faciallandmarkdetection_NativeClass
 * Method:    getMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_harish_faciallandmarkdetection_NativeClass_getMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_harish_faciallandmarkdetection_NativeClass
 * Method:    landmarkDetection
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_harish_faciallandmarkdetection_NativeClass_landmarkDetection
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
